# Generated by Django 5.0 on 2024-01-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usersignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cerat', models.DateField(auto_now_add=True)),
                ('fnm', models.CharField(max_length=20)),
                ('lnm', models.CharField(max_length=20)),
                ('unm', models.CharField(max_length=20)),
                ('cty', models.CharField(max_length=20)),
                ('stat', models.CharField(max_length=20)),
                ('num', models.BigIntegerField()),
            ],
        ),
    ]
